format_version: 4
common:
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks generate_authorization_keys
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan_certs create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
  deploy_and_test_stages: &deploy_and_test_stages
    - deploy:
        clean_workspace: true
        jobs:
          deploy: *deploy_job
    - functional:
        clean_workspace: true
        jobs:
          test:
            resources:
              - docker
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks test_functional
pipelines:
  'prm-deductions-repo-to-gp.dev':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-repo-to-gp
        stage: test_docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages: *deploy_and_test_stages
  'prm-deductions-repo-to-gp.test':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      dev_env:
        pipeline: prm-deductions-system-e2e.dev
        stage: test
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_test
    environment_variables:
      NHS_ENVIRONMENT: test
    stages: *deploy_and_test_stages

